<?php 
/**
 * Template Name: #Category Payload
 *
 * data for the category page on the mobile app.
 *
 * @since  v1.0.0
 * @package Backbone Plugin
 */
if(isset($_GET['v2'])) {
   echo
   '[
      {
         "id":"2",
         "title":"Featured",
         "tag_id":"13",
         "slug":"featured",
         "image_url":"https://cdn.punchng.com/category-icons/featured.png"
      },
      {
         "id":"4",
         "title":"Metro Plus",
         "tag_id":"5",
         "slug":"metro_plus",
         "image_url":"https://cdn.punchng.com/category-icons/metro.png"
      },
      {
         "id":"5",
         "title":"Columns",
         "tag_id":"47",
         "slug":"columns",
         "image_url":"https://cdn.punchng.com/category-icons/columns.png"
      },
      {
         "id":"6",
         "title":"Opinion",
         "tag_id":"17",
         "slug":"opinion",
         "image_url":"https://cdn.punchng.com/category-icons/opinions.png"
      },
      {
         "id":"7",
         "title":"Politics",
         "tag_id":"14",
         "slug":"politics",
         "image_url":"https://cdn.punchng.com/category-icons/politics.png"
      },
      {
         "id":"8",
         "title":"Business",
         "tag_id":"9",
         "slug":"business",
         "image_url":"https://cdn.punchng.com/category-icons/business.png"
      },
      {
         "id":"10",
         "title":"In case you missed it",
         "tag_id":"8775",
         "slug":"in_case_you_missed_it",
         "image_url":"https://cdn.punchng.com/category-icons/incase+you+missed+it.png"
      },
      {
         "id":"11",
         "title":"Interview",
         "tag_id":"72",
         "slug":"interview",
         "image_url":"https://cdn.punchng.com/category-icons/interview.png"
      },
      {
         "id":"12",
         "title":"Sports",
         "tag_id":"3",
         "slug":"sports",
         "image_url":"https://cdn.punchng.com/category-icons/sport.png"
      },
      {
         "id":"13",
         "title":"Interactive",
         "tag_id":"7827",
         "slug":"interactive",
         "image_url":"https://cdn.punchng.com/category-icons/interactive.png"
      },
      {
         "id":"14",
         "title":"Special Feature",
         "tag_id":"39",
         "slug":"special_feature",
         "image_url":"https://cdn.punchng.com/category-icons/special+feature.png"
      },
      {
         "id":"15",
         "title":"Health",
         "tag_id":"38",
         "slug":"health",
         "image_url":"https://cdn.punchng.com/category-icons/health.png"
      },
      {
         "id":"16",
         "title":"Entertainment",
         "tag_id":"46",
         "slug":"entertainment",
         "image_url":"https://cdn.punchng.com/category-icons/entertainment.png"
      },
      {
         "id":"17",
         "title":"Education",
         "tag_id":"11",
         "slug":"education",
         "image_url":"https://cdn.punchng.com/category-icons/education.png"
      },
      {
         "id":"18",
         "title":"Technology",
         "tag_id":"28",
         "slug":"technology",
         "image_url":"https://cdn.punchng.com/category-icons/technology.png"
      },
      {
         "id":"19",
         "title":"Editorial",
         "tag_id":"22",
         "slug":"editorial",
         "image_url":"https://cdn.punchng.com/category-icons/editorial.png"
      },
      {
         "id":"20",
         "title":"Panorama",
         "tag_id":"50760",
         "slug":"panorama",
         "image_url":"https://cdn.punchng.com/category-icons/panorama.png"
      },
      {
         "id":"21",
         "title":"Sex and Relationship",
         "tag_id":"8784",
         "slug":"sex_and_relationship",
         "image_url":"https://cdn.punchng.com/category-icons/sex%26relationship.png"
      },
      {
         "id":"22",
         "title":"Videos",
         "tag_id":"116",
         "slug":"videos",
         "image_url":"https://cdn.punchng.com/category-icons/videos.png"
      }
   ]';

}
else {

   echo
   '[
      {
         "id":"2",
         "title":"Featured",
         "tag_id":"13",
         "slug":"featured",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"4",
         "title":"Metro Plus",
         "tag_id":"5",
         "slug":"metro_plus",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"5",
         "title":"Columns",
         "tag_id":"47",
         "slug":"columns",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"6",
         "title":"Opinion",
         "tag_id":"17",
         "slug":"opinion",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"7",
         "title":"Politics",
         "tag_id":"14",
         "slug":"politics",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"8",
         "title":"Business",
         "tag_id":"9",
         "slug":"business",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"10",
         "title":"In case you missed it",
         "tag_id":"8775",
         "slug":"in_case_you_missed_it",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"11",
         "title":"Interview",
         "tag_id":"72",
         "slug":"interview",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"12",
         "title":"Sports",
         "tag_id":"3",
         "slug":"sports",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"13",
         "title":"Interactive",
         "tag_id":"7827",
         "slug":"interactive",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"14",
         "title":"Special Feature",
         "tag_id":"39",
         "slug":"special_feature",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"15",
         "title":"Health",
         "tag_id":"38",
         "slug":"health",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"16",
         "title":"Entertainment",
         "tag_id":"46",
         "slug":"entertainment",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"17",
         "title":"Education",
         "tag_id":"11",
         "slug":"education",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"18",
         "title":"Technology",
         "tag_id":"28",
         "slug":"technology",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"19",
         "title":"Editorial",
         "tag_id":"22",
         "slug":"editorial",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"20",
         "title":"Panorama",
         "tag_id":"50760",
         "slug":"panorama",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"21",
         "title":"Sex and Relationship",
         "tag_id":"8784",
         "slug":"sex_and_relationship",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      },
      {
         "id":"22",
         "title":"Videos",
         "tag_id":"116",
         "slug":"videos",
         "image_url":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIsf1eWyEXux_PJQrqaKR7ucMU39ZmItuVkA&usqp=CAU"
      }
   ]';
   
}